version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app/
      - river_node_modules:/usr/app/node_modules
    ports:
      - '8080:8080'

volumes:
  river_node_modules:
